def passwordcheckonly(password):
    if password == '1234':
        return True
        

    else :
        return False
okstatus=passwordcheckonly('1234')
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
print(okstatus)
s
s
s
print(okstatus)
print(okstatus)
print(okstatus)
okstatus=passwordcheckonly('1234')


